[build]
    publish = "public/"
    command = "yarn run build"
[[headers]]
    for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
[[headers]]
    for = "/"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
[[headers]]
    for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, stale-while-revalidate=2592000"
[[headers]]
    for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, stale-while-revalidate=2592000"
[[headers]]
    for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, stale-while-revalidate=2592000"
[[headers]]
    for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, stale-while-revalidate=2592000"
[[redirects]]
  from = "https://toddmath.netlify.com/*"
  to = "https://www.toddmath.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "http://toddmath.netlify.com/*"
  to    = "https://www.toddmath.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "http://www.toddmath.netlify.com/*"
  to = "https://www.toddmath.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.toddmath.netlify.com/*"
  to = "https://www.toddmath.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://toddmath.com/*"
  to = "https://www.toddmath.com/:splat"
  status = 301
  force = true
